steps:

- id: "Rodando install"
  name: "gcr.io/cloud-builders/go"
  args: ["install", "soma"]
  env: ["GOPATH=."]

- id: "Rodando Test"
  name: "gcr.io/cloud-builders/go"
  args: ["test", "soma"]
  env: ["GOPATH=."]